global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: skillbridge-app
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:10000']